### ISSUE TITLE
Module not finding the .dll-Help.xml

### ISSUE THREAD

**Issue by dotps1** [nightroman/Helps#7]
Thanks for the awesome module, its really nice, but after i convert-helps and place it in my ModuleDIr\en-US\Module.dll-Help.xml, my commands do not seem to be using the file, do i need to add something to my manifest perhaps?

Thanks.

**Comment by nightroman** [comment]
Hmm... I do not add anything specific. Perhaps there is a way to specify a help file for commands explicitly. But before we go there, what is your current UI culture? Is it *en-US*? Take a look at `$Host.CurrentUICulture`. And, in any, case. Does it help if you put your xml together with DLL, in the same directory.

And of course double check that all names are the same (DLL and help file match, command name in DLL and help file match, etc.)

**Comment by dotps1** [comment]
$host.CurrentUICultrue returnes en-US.  my module is a script module so it is not a .dll, should that matter?  i am going to strip every thing out of it, and make it just the Synopsis once, just to rule out the xml.
thanks for you help.

**Comment by dotps1** [comment]
OMG, i figured it out.  i was converting my Comment Based Help into XML Based help, and i had the word .PARAMETER spelled wrong in a different function in the module,  that was preventing the import.  man, i wasted hours on this.

**Comment by nightroman** [comment]
I am glad it is resolved. So one of your functions still had comment based help with a misspelled keyword, right? It's yet another reason why the *Helps.ps1* approach may have advantage over comment based helps, it fails to compile if something is wrong.

**Comment by dotps1** [comment]
there was one other issue, the fact that my module was a Script Module (.psm1) and not a complied dll.  my help file has to  be named
```
ModuleName-Help.xml
```

thanks again!
