### ISSUE TITLE
PowerShell Gallery Module

### ISSUE THREAD

**Issue by mattmcnabb** [nightroman/Helps#9]
Why not package the commands in helps.ps1 as a module and publish this in the Gallery? It would make downloading and importing much easier.

Thanks!

**Comment by nightroman** [comment]
> It would make downloading and importing much easier.

I agree.

Honestly, I tend to avoid script modules in public projects. They have subtle issues. When things are simple all normally looks fine. Then on adding complex features or in complex scenarios one finds something wrong and it is too late or just painful to redo.

Nevertheless, I will think of packaging as a module. But this is not so cosmetic job as it looks even for such a simple tool as Helps.

**Comment by nightroman** [comment]
I have tried to convert `Helps` to a module. This is simple, it is enough to
create `Helps.psm1` and dot-source `Helps.ps1`. Then I tested it. Most of
things worked. But some problems were found, too.

One of the problems is described in [PowerShellTraps/../Function-not-found-2](https://github.com/nightroman/PowerShellTraps/tree/master/Module/Function-not-found-2).

In other words, in some cases a function that we try to create help for is not
found when we use `Helps` as a module. When we use it as a dot-sourced script
then it works as expected.

As far as `Helps` is all about finding and analysing user commands including
functions and PowerShell modules have difficulties with this, `Helps` should
not be packaged a module.

Robustness of the current script is more important than *slightly* easier
downloading and importing.

**Comment by mattmcnabb** [comment]
Thanks Roman! I never would have expected the issue you described. I suppose dot-sourcing a script will work just fine.

**Comment by nightroman** [comment]
I am about to change my mind and publish the tool at PSGallery.

I am pretty sure that subtle issues related to script modules are still there. But I am going to keep the script library behind the scene. As a result:

1. The module is going to wrap the library. Actual workers will be script functions, like now. This should reduce chances of potential problems (hopefully).
2. The current script *Helps1.ps1* will be in the package. So even if module problems exist, one may use it directly as it is used now.

**Comment by nightroman** [comment]
OK, I have tried it again. When it is implemented as a module, even with the original script behind, it does not see some commands that we build help for. For now, I give up and close it again. Do not repair what works...

**Comment by nightroman** [comment]
I will keep the changes for a while https://github.com/nightroman/Helps/tree/171111-issue9-module

The Help module commands do not see functions defined in the parent scope. Maybe it is not a problem in many cases. But it serious limitation. Script edition works in all known cases. Let's keep it this way.
